### ISSUE TITLE
Master Rank needed

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#19]
**Description**
When adding/editing an armor, there are only 2 rank options available: "High" and "Low". Since _Monster Hunter World: Iceborne_ introduces the "Master" rank, it would be great if the same option could be provided.

**Preferred solution**
The "Master" rank should be provided when adding or editing an armor.

**Screenshots**
<img width="563" alt="螢幕快照 2019-09-10 上午1 44 46" src="https://user-images.githubusercontent.com/40516784/64554427-f9f52780-d36d-11e9-86f2-fca38cb0e320.png">

**Comment by LartTyler** [comment]
Since this is going to require changes to both the editor and the backend (since validation will need to be changed to allow master rank), this will be part of the API's 1.16.0 release. You can follow the progress [here](https://github.com/LartTyler/MHWDB-API/pull/99), and I'll also keep you posted in this thread. I should have it out in the next couple of days, once the editor is updated to support the changes made by 1.16.0.

**Comment by mingjunlu** [comment]
I'll start adding new armors after those changes are made. Looking forward to the release! 🤠

**Comment by LartTyler** [comment]
Master rank should now be available in the editor with [v1.3.0](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.3.0). You may need to clear your cache in order to see it.
