### ISSUE TITLE
Blank screen when adding rank to armor set bonus

### ISSUE THREAD

**Issue by mingjunlu** [LartTyler/MHWDB-Contrib#26]
**Description**
The entire screen goes blank when a new rank is added to an armor set bonus.

**To Reproduce**
1. Go to "Objects > Armor Set Bonuses"
2. Click on "Add New" button
3. Click on "Add Rank" button

**Expected behavior**
A new rank should be added to the armor set bonus.

**Screenshots**
<img width="752" alt="螢幕快照 2019-09-10 上午10 54 36" src="https://user-images.githubusercontent.com/40516784/64621134-bce56f80-d417-11e9-8df1-d4fec309071d.png">

**Environment**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari 12.1.2 & Vivaldi 2.7.1628.33

**Comment by LartTyler** [comment]
I believe this is resolved with [v1.2.3](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.2.3). I think this was happening because the "Add Rank" button could be clicked before the skills were fully loaded from the API, but I was having a hard time recreating the issue. Would you be able to test it out for me on the live site and confirm that it's resolved?

**Comment by mingjunlu** [comment]
I think you're right about the cause. I just tested it on the live site. Problem solved. Nice work!
